name: XMvideo
options:
  bundleIdPrefix: com.xmvideo
  deploymentTarget:
    macOS: "11.0"
  
targets:
  XMvideo:
    type: application
    platform: macOS
    sources:
      - XMvideo
    info:
      path: XMvideo/Info.plist
      properties:
        CFBundleName: XMvideo
        CFBundleDisplayName: XMvideo
        CFBundleIdentifier: com.xmvideo.XMvideo
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0.0"
        LSMinimumSystemVersion: "11.0"
        LSUIElement: true
        NSHumanReadableCopyright: "Copyright © 2026 XMvideo. All rights reserved."
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.xmvideo.XMvideo
      MARKETING_VERSION: "1.0.0"
      CURRENT_PROJECT_VERSION: "1"
      SWIFT_VERSION: "5.0"
      MACOSX_DEPLOYMENT_TARGET: "11.0"
      ENABLE_HARDENED_RUNTIME: YES
      COMBINE_HIDPI_IMAGES: YES
